In [1]:
from numpy import diag,array,dot
from scipy.linalg import svd
a=array(([1,2],[3,4],[5,6]))
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [2]:
u,s,vt=svd(a)

In [3]:
print('matrix u \n',u)
print('matrix v \n',vt)
print('matrix s \n',s)

matrix u 
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
matrix v 
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
matrix s 
 [9.52551809 0.51430058]


In [4]:
import numpy as np
sigma=np.zeros((a.shape[0],a.shape[1]))
print(sigma)
print(sigma.shape)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)


In [5]:
a.shape[1]

2

In [6]:
print(diag(s))

[[9.52551809 0.        ]
 [0.         0.51430058]]


In [7]:
sigma[:a.shape[1],:a.shape[1]]=diag(s)

In [8]:
sigma

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [9]:
a_mos=u.dot(sigma.dot(vt))
a_mos

array([[1., 2.],
       [3., 4.],
       [5., 6.]])